name: C/C++ CI

on:
  push:
    branches: 
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DEVKITPRO: /opt/devkitpro
    steps:
    - name: Checkout Master
      uses: actions/checkout@v1
      
    - name: Download DEVKITPRO
      run: wget https://github.com/devkitPro/pacman/releases/download/devkitpro-pacman-1.0.1/devkitpro-pacman.deb
      
    - name: Install DEVKITPRO
      run: sudo dpkg -i devkitpro-pacman.deb
      
    - name: Install dkp-pacman
      run: printf "\nY" | sudo dkp-pacman -S switch-dev switch-freetype
      
    - name: Make
      run: make
      
    - name: ZIP Release
      run: zip -r sys-logger.zip sdcard_out pctools/client.py
      
    - name: Upload Release
      uses: meeDamian/github-release@v1.0.1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        tag: canary
        body: >
          Canary build of sys-logger. Updated each time a commit is pushed to `master`
        gzip: false
        files: sys-logger.zip
        allow_override: true
        name: >
          [Canary] sys-logger
